### ISSUE TITLE
newer SIMD architectures missing from wheels

### ISSUE THREAD

**Issue by rgommers** [MacPython/numpy-wheels#107]
I was looking at wheel sizes and was surprised that the 1.20 wheels were barely larger than the 1.19 ones. I can't remember we have taken a decision on what SIMD architectures to include in wheels, however I'd expect it to include at least AVX2. This is what I see on macOS right now:
```
>>> np.__version__
'1.20.1'
>>> np.core._multiarray_umath.__cpu_baseline__
['SSE', 'SSE2', 'SSE3']
```

I think it's similar on other platforms, we didn't update this repo with a new baseline. Thoughts @seiko2plus, @mattip?

**Comment by mattip** [comment]
Try `__dispatch__`, which is the maximum set of features. For a local build on linux x86_64 this shows me
```
>>> np.core._multiarray_umath.__cpu_dispatch__
['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', \
 'AVX512_KNL', 'AVX512_KNM', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL']
```

**Comment by rgommers** [comment]
Thanks. That gives me the the same result with the released macOS wheel. With that many extra architectures, I'm then a little surprised the difference is only ~400 kb. Is that expected?

**Comment by seiko2plus** [comment]
> Is that expected?

yes, since we have not expanded using the new CPU dispatcher yet, just a few SIMD kernels.

**Comment by rgommers** [comment]
Thanks for the answers @mattip and @seiko2plus. Nothing to do here then, let me close this.
