### ISSUE TITLE
The aarch nightly wheels are uploading to the wrong repo.

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#111]
For the last several weeks the aarch nightly wheels have been uploading to the staging repo.

**Comment by charris** [comment]
Probably due to the renaming of master to main.

**Comment by charris** [comment]
I've renamed master to main in the numpy-wheels repo, let's see if that fixes things.

**Comment by charris** [comment]
@mattip Can you make the nightly upload token available to the `main` branch? I'd do it myself, but a new entry needs to be made and I don't know what the value is.

**Comment by mattip** [comment]
I added a token for main to https://travis-ci.com/github/MacPython/numpy-wheels/settings to upload to https://anaconda.org/scipy-wheels-nightly/numpy. That is for the weekly (misnamed "nightly") builds.

**Comment by charris** [comment]
@mattip Thanks.

**Comment by charris** [comment]
The last PyPy wheel build failed with `METH_FASTCALL`, should we update the ty PyPy version?

**Comment by mattip** [comment]
make sense.

I also updated the comments about the tokens in the .travis.yml

**Comment by mattip** [comment]
> should we update the the PyPy version

I don't know if we can get a new enough PyPy in the multibuild system. I should be releasing a new version soon

**Comment by charris** [comment]
Working now, closing.
