### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by mattip** [MacPython/numpy-wheels#116]
It would be nice to be able to use the newest python versions to build wheels. For linux, these are available via the manylinux wheels, which are updated pretty quickly after a python release. But for windows and macOS, we need python executables via the CI. Azure tends to lag behind github actions, so perhaps we should move the CI builds to github actions before the release of Python 3.10

**Comment by rgommers** [comment]
Should we just do that if and when GitHub Actions gets 3.10? Until that time it's just busywork right?

Another consideration is doing the same as on the main repo, if we have Windows only on Azure in main CI, then we may want to be careful about building wheels on GHA.

**Comment by charris** [comment]
> Should we just do that if and when GitHub Actions gets 3.10?

GitHub Actions has supported the releases since a1 and so has azure-pipelines (for linux). The tricky bit will be support on Windows and Mac.  We could try GitHub Actions for that just to see if it works.

**Comment by mattip** [comment]
Closing. Hopefully we will be building wheels on the numpy/numpy repo.
