### ISSUE TITLE
Headers in universal2 wheels are not architecture independent

### ISSUE THREAD

**Issue by isuruf** [MacPython/numpy-wheels#140]
Since auto-generated file `_numpyconfig.h` has `NPY_SIZEOF_LONGDOUBLE` and `NPY_SIZEOF_COMPLEX_LONGDOUBLE` generated, it's wrong for x86_64 as the universal2 wheel distributes the arm64 version of it.

Easiest option would be to stop distributing universal2 wheels and only distribute thin wheels.

**Comment by isuruf** [comment]
We can ignore universal2 wheels also because if pip prefers thin wheels over universal2 wheels if the thin wheel exist.

**Comment by tylerjereddy** [comment]
Ah ok, this would make sense as the source of the problems based on some back and forth with @charris as well

**Comment by rgommers** [comment]
Thanks for tracking that one down!

> Easiest option would be to stop distributing universal2 wheels and only distribute thin wheels.

That's fine with me. Probably a good thing in the long run; universal2 is a bit pointless, just increases download sizes.

**Comment by isuruf** [comment]
Or we merge https://github.com/numpy/numpy/pull/20270

**Comment by isuruf** [comment]
In the meantime we should either upload a thin wheel or yank `numpy-1.21.3-cp310-cp310-macosx_10_9_universal2.whl`

**Comment by charris** [comment]
@isuruf Do you know if rosetta supports extended precision long doubles? We ran into a problem with cpp where we needed to use `typedef long double npy_longdouble`, which I am thinking may have been a wrong workaround.

**Comment by isuruf** [comment]
Yes.

```zsh
(base) idf2@M1MD ~ % cat asd.cpp         
#include<iostream>
  
int main()
{
    long double eps = 0.5;
    while ((1+eps) != 1)
    {
        eps /=2;
    }
    std::cout << eps*2 << std::endl;
}
(base) idf2@M1MD ~ % clang++ asd.cpp -arch arm64 -arch x86_64
(base) idf2@M1MD ~ % arch -x86_64 ./a.out                    
1.0842e-19
(base) idf2@M1MD ~ % arch -arm64 ./a.out                     
2.22045e-16
```

**Comment by charris** [comment]
@isuruf I'm happy to do both. Do the thin 3.10 builds work now?

**Comment by isuruf** [comment]
You'll have to use https://github.com/multi-build/multibuild/pull/438 to get a thin wheel with 3.10

**Comment by charris** [comment]
I've merged #20270. I'll trigger a nightly build so it can be tested.

**Comment by charris** [comment]
@isuruf Is there a problem getting https://github.com/multi-build/multibuild/pull/438 merged?

**Comment by isuruf** [comment]
Nope. Just needs a review

**Comment by EwoutH** [comment]
https://github.com/multi-build/multibuild/pull/438 was merged yesterday!

**Comment by charris** [comment]
Both numpy and multibuild have been updated to deal with this.
