### ISSUE TITLE
Update multibuild to a version that strips binaries in wheels

### ISSUE THREAD

**Issue by xhochy** [MacPython/numpy-wheels#19]
On the next release, please update the multibuild submodule to matthew-brett/multibuild@b2748e5 or newer. This should reduce the size of the numpy wheels from 16,1M to 12M by excluding unnecessary debug symbols.

**Comment by charris** [comment]
Which multibuild branch?

**Comment by xhochy** [comment]
The current HEAD of devel includes this.

**Comment by charris** [comment]
Done.
