### ISSUE TITLE
C compiler not found for f2py tests.

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#22]
The C compiler detection of f2py is failing, hence all tests in `test_array_from_pyobj.py` are being skipped. This is not new with pytest.

**Comment by tylerjereddy** [comment]
I think the C compiler messages are a red herring -- I've confirmed that `gfortran` is missing in Matthew Brett's docker container when the tests run on linux. If I install gfortran with aptitude, the f2py tests all pass instead of skip.

**Comment by mattip** [comment]
This can be closed?

**Comment by tylerjereddy** [comment]
Pretty sure I've fixed this yeah.
