### ISSUE TITLE
macOS wheel naming incorrectly includes 10.6

### ISSUE THREAD

**Issue by rgommers** [MacPython/numpy-wheels#43]
See https://github.com/numpy/numpy/issues/12939

**Comment by mattip** [comment]
I think this can be closed. The [wheels](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/) after Aug 2019 are properly named. Please reopen if there is more action needed

**Comment by mattip** [comment]
Sorry, I meant Oct 2019.
