### ISSUE TITLE
Scheduled Wheels Builds on Windows

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/numpy-wheels#47]
This came up in https://github.com/pandas-dev/pandas/issues/26546

Both NumPy and SciPy only do scheduled builds on Travis (Linux / Mac) but not on Appveyor (Windows), so regular master branch wheels / binaries are not available consistently on Windows for i.e., debugging downstream, etc.

It looks like [appveyor team wants to be contacted directly by OSS projects](https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/) that want scheduled builds to avoid wasted cycles on abandoned projects with scheduled builds.

See also: https://www.appveyor.com/docs/build-configuration/#scheduled-builds

Not sure if it is much easier on Azure or not.

**Comment by mattip** [comment]
Azure pipelines has [scheduled triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers). I am not sure how this plays with the regular [pr trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pr-triggers). I can try to set this up.

**Comment by tylerjereddy** [comment]
Maybe not a bad idea--of course, switching some / much of the wheel build infrastructure to Azure will probably come at some cost with new problems initially.

**Comment by charris** [comment]
Closing. This should be fixed with the move to azure.
