### ISSUE TITLE
wheels.scipy.org outdated

### ISSUE THREAD

**Issue by rgommers** [MacPython/numpy-wheels#48]
I may be forgetting some bit of history here, but right now http://wheels.scipy.org/ contains only outdated wheels (till Dec 2018 for `numpy-1.17.0.dev`) while https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/ is up to date.

Do we need to point wheels.scipy.org to the new place? Can anyone summarize what happened here?

**Comment by charris** [comment]
NumPy 1.16.4 from last week is at http://wheels.scipy.org, which is for releases. The nightlys are at the rackcdn link.

**Comment by rgommers** [comment]
Ah yes it is, thanks @charris. I just don't know how those ~10 1.17.0.dev0 builds ended up there. @matthew-brett maybe you can delete them? I think you're the only one with access?

**Comment by charris** [comment]
> I just don't know how those ~10 1.17.0.dev0 builds ended up there. 

I'm guessing from merging PRs or testing.

**Comment by matthew-brett** [comment]
I've deleted the dev files.

For the credentials - who should I pass these to, so you don't depend on me being online?

**Comment by rgommers** [comment]
Thanks Matthew. Perhaps just pass them on to me? Bus factor of 2 will be fine I think. And probably it's more already anyway, I just don't know who else would have access.

**Comment by matthew-brett** [comment]
Have shared it with you (Ralf) on Google drive, let me know if you've got it.   @ogrisel - I was sure you'd agree to me sharing with Ralf, but please let us know if I was wrong.  Ralf, the credentials belong to scikit-learn; @ogrisel gave them to me, and I ask him when in doubt about sharing them.

**Comment by ogrisel** [comment]
Sorry for the late reply but yes I agree :)

**Comment by mattip** [comment]
Close?

**Comment by rgommers** [comment]
yep seems fixed
