### ISSUE TITLE
win32 should have a _distributor_init.py and preload DLLs

### ISSUE THREAD

**Issue by mattip** [MacPython/numpy-wheels#49]
fixes numpy/numpy#13764

In numpy/numpy#13109 we preload any dlls as a way around other methods of solving dll hell. That code should live here, as part of a `_distributor_init.py` file. In addition, the win32 CI run should run a sanity check on the wheel it builds in a clean environment.

The transferred code should also add a `try except` for the case where `__file__` does not exist.

**Comment by mattip** [comment]
PR #50 was meant to fix this, but looking at the [artifact], the _distributor_init.py was not overwritten.

**Comment by mattip** [comment]
The _distributor_init.py is now overwritten but the contents are not correct

**Comment by charris** [comment]
What should it be? I can see the contents by downloading the wheel created after merge from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/

**Comment by mattip** [comment]
See PR #52 - I found the base directory improperly

**Comment by charris** [comment]
I see libopenblas.FN5FF57TWHUYLRG54LA6B33EZPHYZZL4.gfortran-win32.dll, which is not correct. I wonder where that came from.

**Comment by mattip** [comment]
I am pretty sure that is the dll we have been shipping, the problem was I was looking for `.libs` one directory higher

**Comment by charris** [comment]
We should be shipping libopenblas_v0.3.5-gcc_7_1_0.dll, does it get renamed somewhere?

**Comment by charris** [comment]
OK, that looks correct, agrees with 1.16.4. So it does get renamed along the line somewhere.
