### ISSUE TITLE
python3.8 wheels for osx, windows

### ISSUE THREAD

**Issue by mattip** [MacPython/numpy-wheels#63]
It seems we should be able to use multibuild to build osx wheels for python3.8 with the following diff. Multibuild supports 3.8 on OSX since matthew-brett/multibuild#262 (which is badly named)
```
diff --git a/.travis.yml b/.travis.yml
index 6b19a35..7eaae8d 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -63,6 +63,11 @@ matrix:
       env:
         - MB_PYTHON_VERSION=3.7
         - MB_PYTHON_OSX_VER=10.9
+    - os: osx
+      language: generic
+      env:
+        - MB_PYTHON_VERSION=3.8
+        - MB_PYTHON_OSX_VER=10.9
 
 before_install:
     - if [ "$TRAVIS_BRANCH" == "master" ]; then

```

**Comment by mattip** [comment]
multibuild now supports 3.80rc1 on windows as well, so this should work as well
```
diff --git a/.appveyor.yml b/.appveyor.yml
index 035fa86..d3611f6 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -50,6 +50,14 @@ environment:
       PYTHON_VERSION: 3.5
       PYTHON_ARCH: 64
 
+    - PYTHON: C:\Python38rc1
+      PYTHON_VERSION: 3.8
+      PYTHON_ARCH: 32
+
+    - PYTHON: C:\Python38rc1-x64
+      PYTHON_VERSION: 3.8
+      PYTHON_ARCH: 64
+
 init:
   - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
   - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
```

**Comment by charris** [comment]
Should OS-X work also?

**Comment by mattip** [comment]
yup, both these diffs should be good to go

**Comment by charris** [comment]
Windows looks to be having a problem: https://ci.appveyor.com/project/charris/numpy-wheels/builds/27959206/job/vti22nsfjwawvv3e

**Comment by charris** [comment]
We will probably need @matthew-brett to shut down the stuck Windows build. We've seen this before :)

**Comment by matthew-brett** [comment]
The RC1 download URL looks wrong in the log :
https://www.python.org/ftp/python/3.8.0rc1/python-3.8.0rc1.exe

**Comment by charris** [comment]
Looks like it should be https://www.python.org/ftp/python/3.8.0/python-3.8.0rc1.exe

**Comment by stefanv** [comment]
I've opened a new issue for that [here](https://github.com/MacPython/numpy-wheels/issues/65) so that this discussion can be closed.
