### ISSUE TITLE
travis builds not triggered for v1.18.x branch

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#75]
@matthew-brett @mattip Were any changes made to the travis trigger that you know of? Thoughts?

**Comment by mattip** [comment]
One cause could be a typo in the travs.yml file.

**Comment by tylerjereddy** [comment]
I tried pasting the `.travis.yml` for both that branch and master into their parser: https://config.travis-ci.com/explore

It didn't seem to find any fatal errors.

**Comment by charris** [comment]
I fixed the triggering by using `xenial` and `jobs` in the `travis.yml`, not sure which change made a difference, but suspect `jobs`. However the build is now failing, see https://travis-ci.org/MacPython/numpy-wheels/jobs/660440686. Has there been a change in the docker image? Do I need to run a more recent version of multibuild?

**Comment by charris** [comment]
OK, probably need the pip 20 fix. Trying...

**Comment by charris** [comment]
@tylerjereddy If you do another scipy 1.4 release you might have the same problems.

**Comment by tylerjereddy** [comment]
Ah yes, I've seen that one. I think we patched on our master wheels branch for SciPy but maybe not the 1.4.x branch. Thanks for the reminder, if that crops up.
