### ISSUE TITLE
Moving from rackspace

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#77]
@mattip @tylerjereddy 

I need to start preparing `numpy-wheels` master for the 1.19 release. There are a couple of things that need fixing or decisions.

- Should wheel uploads go to the new anaconda repo?
- Do we need https://anaconda.org/multibuild-wheels-staging/numpy?
- What needs to be changed to use the libraries on anaconda?
- Should 1.19 stick with manylinux2010 or fall back to manylinux1 for working 32 bit NumPy?

Pandas looks to have uploaded the recent pandas to anaconda, maybe we can steal some code from them.

**Comment by tylerjereddy** [comment]
Yeah, I'm starting to fall behind a bit on this task for SciPy. I have WIP MR for some migration tasks: https://github.com/MacPython/scipy-wheels/pull/69 but I've been neglecting it.

**Comment by mattip** [comment]
Yes, we should migrate to anaconda. 

As for manylinux2010 or manylinux1: Can we  release both for 1.19? We only need to build once, and can repackage the wheel using `auditwheel repair --plat <tag>` for manylinux1. This will add 2 more wheels, which should not be too big a burden.

I don't think the other arch PR gh-74 will be ready: aarch64 and ppc64le builds still fail, but I would like to push forward with the x86_64/macOS/win32 PyPy wheels.

**Comment by mattip** [comment]
Looking at what [pandas-wheels](https://github.com/MacPython/pandas-wheels) now does:
- they moved off travis and appveyor and now only build on azure
- they still use multibuild, but via azure/posix.yml

I think this is reasonable to adapt to numpy-wheels. We would have to revisit travis if/when we get the other architectures to work. I am working on gh-78 and have added the azure integration to try this out.

**Comment by rgommers** [comment]
Do we really still need `manylinux1` wheels? IIRC the discussion before (not sure for numpy or scipy) we were fine with moving to `manylinux2010`. CentOS5 is super obsolete, it stopped getting security patches in 2017, so I think it's really pointless to support by now.

**Comment by mattip** [comment]
The only reason to ship `manylinux1` wheels is that installing `manylinux2010` wheels depends on `pip>19.0`, which was released Jan 2019.

**Comment by rgommers** [comment]
Oh yes, fun. Okay makes sense, thanks for the reminder.

**Comment by mattip** [comment]
I think we can close this.
