### ISSUE TITLE
terryfy needs fixing to work with anaconda.

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#92]
Probably just needs a UserAgent for wheeluploader. I think we may want to build our own downloader and put it in the numpy tools directory.

**Comment by charris** [comment]
If NumPy has its own downloader in tools, I think all we really need is the numpy version and just download all the files with that version.

**Comment by charris** [comment]
Also, I wonder about the URL, as it doesn't show the raw files, but rather an interface to them. Note that it is possible to download the files one at a time manually, so that can serve when nothing else is available.

**Comment by tylerjereddy** [comment]
I'm keeping an eye on what you do here--maybe I can "borrow" whatever solution you come up with for SciPy.

**Comment by charris** [comment]
@ogrisel Thoughts?

**Comment by charris** [comment]
I think the easiest thing is to make a `tools/download_wheels.py` module. A lot can probably be stolen from the  `support_openblas.py` module.

**Comment by charris** [comment]
OK, I can get the list of files and download them. I'm tempted to put this in the pavement file.

**Comment by charris** [comment]
Have a working prototype. It is stripped down, just downloads all the numpy wheels of a given version that are in the staging directory.

**Comment by charris** [comment]
See https://github.com/numpy/numpy/pull/16265.
