### ISSUE TITLE
Travis branch builds do not upload to anaconda

### ISSUE THREAD

**Issue by charris** [MacPython/numpy-wheels#93]
Looks like the `NUMPY_STAGING_UPLOAD_TOKEN` is missing. The builds are triggered, they just don't upload. See https://travis-ci.org/github/MacPython/numpy-wheels.

**Comment by charris** [comment]
I suspect the tokens are only enabled for master, they need to be enabled for all branches.

**Comment by mattip** [comment]
Fixing. https://travis-ci.org/github/MacPython/numpy-wheels/settings

**Comment by mattip** [comment]
Restarted

**Comment by charris** [comment]
Thanks. We should probably add a cron job as well.

**Comment by mattip** [comment]
I see a weekly cron job off master in the settings link

**Comment by charris** [comment]
> I see a weekly cron job off master in the settings link

I see it now. Could you edit the variables without deleting and readding? I couldn't do that.

**Comment by charris** [comment]
Note that I needed to remove the trigger section of azure in order for it to trigger on the v1.19.x branch, didn't want the hassle of specifying all the branches.

**Comment by mattip** [comment]
> Could you edit the variables without deleting and readding?

Nope. I had to delete it, go to https://anaconda.org/multibuild-wheels-staging/settings/access and get the value, then re-add it.

**Comment by mattip** [comment]
The 4 travis wheels uploaded

**Comment by charris** [comment]
Not too bad all and all, I probably should have tested the whole workflow earlier. Thanks for your prompt help on this.
